version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - seccomp=./chrome.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - web
    # command: npm run start

networks:
  web:
    driver: bridge